---
title: HHJ Mediations
timezone: UTC
collections:
  education:
    title: Education
    output: true
  experience:
    title: Experience
    output: true
  posts:
    title: Posts
    output: true
  specialties:
    title: Specialties
    output: true
  uploads:
    title: Uploads
    output: true
email: hhj@hhjmediations.com
description: Mediations, arbitration, and disupte resolutions in West Virginia
baseurl: ''
url: https://hhjmediations.com
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
