---
title: HHJ Mediations
timezone: UTC
collections:
  education:
    title: Education
    output: true
  experience:
    title: Experience
    output: true
  posts:
    title: Posts
    output: true
  specialties:
    title: Specialties
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: experience
  values:
    institution: ''
    time-period: ''
email: hhj@hhjmediations.com
description: Mediations, arbitration, and disupte resolutions in West Virginia
baseurl: ''
url: https://adamglenn.github.io/hhjmediations/
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
destination: "./docs"
incremental: false
regenerate: true
