---
title: HHJ Mediations
timezone: UTC
collections:
  contact-info:
    title: Contact Info
    output: true
  education:
    title: Education
    output: true
  experience:
    title: Experience
    output: true
  honors-and-awards:
    title: Honors & Awards
    output: true
  licenses-and-certificates:
    title: Licenses and Certificates
    output: true
  organizations:
    title: Organizations
    output: true
  posts:
    title: Posts
    output: true
  specialties:
    title: Specialties
    output: true
  uploads:
    title: Uploads
    output: true
  volunteering:
    title: Volunteering
    output: true
defaults:
- scope:
    path: ''
    type: experience
  values:
    institution: ''
    time-period: ''
- scope:
    path: ''
    type: education
  values:
    degree: ''
- scope:
    path: ''
    type: volunteering
  values:
    organization: ''
- scope:
    path: ''
    type: organizations
  values:
    role: ''
email: hhj@hhjmediations.com
description: Mediations, arbitration, and disupte resolutions in West Virginia
baseurl: 
url: https://adamglenn.github.io/hhjmediations/
facebook_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/heatherheiskelljones/
address_line_1: 11 Moosemont Road
address_line_2: Charleston, WV 25304
phone: (304) 545-9393
theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
destination: "./docs"
incremental: false
regenerate: true
